name: Update Google Sheet

# 5분마다 실행되도록 설정
on:
  schedule:
  # 매일 새벽 4시(KST)에 실행되도록 설정 (UTC 19시)
  - cron: '0 19 * * *'
  
  # 매일 새벽 4시(KST)에 실행되도록 설정 (UTC 19시)
  #  - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  update-google-sheet:
    runs-on: ubuntu-latest

    steps:
    # 코드 체크아웃
    - name: Check out code
      uses: actions/checkout@v3

    # Python 세팅 (여기서 3.10 버전 사용)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # 필요한 패키지 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Python 스크립트 실행
    - name: Run Update Google Sheet
      run: python main.py
